=== zw-cn/JavaBasic/17.XML/src/com/zw/xml/test02_dtd/score.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT students (student+)>
        <!ELEMENT student (name, course, score)>
        <!ATTLIST student id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT course (#PCDATA)>
        <!ELEMENT score (#PCDATA)>

=== zw-cn/JavaBasic/17.XML/src/com/zw/xml/test02_dtd/outerDTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--引入外部DTD文件-->
<!DOCTYPE students SYSTEM "Score.dtd">
<students>
    <student id="1">
        <name>王同</name>
        <course>java</course>
        <score>89</score>
    </student>
    <student id="2">
        <name>李佳</name>
        <course>sql</course>
        <score>58</score>
    </student>
</students>
